version: "3.7"

services:

    snmp:
      image: snmp-poller
      container_name: snmp-poller
      ports:
        - 9998:9998
      volumes:
        - /Users/beelder/docker-projects/snmp-poller/config.yml:/usr/bin/app/config.yml
      restart: always
