{
 "title": "cBR8 Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "All cBR8s",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "Cisco-IOS-XE-docsis-oper:docsis-oper-data/cm-summary-total",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Registered",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "Cisco-IOS-XE-docsis-oper:docsis-oper-data/cm-summary-total",
     "select": [
      [
       {
        "params": [
         "cm_if_summary_totals/registered"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wideband",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "Cisco-IOS-XE-docsis-oper:docsis-oper-data/cm-summary-total",
     "select": [
      [
       { "params": [ "wideband" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TFTP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "Cisco-IOS-XE-docsis-oper:docsis-oper-data/cm-summary-total",
     "select": [
      [
       { "params": [ "inito" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "DHCP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "Cisco-IOS-XE-docsis-oper:docsis-oper-data/cm-summary-total",
     "select": [
      [
       { "params": [ "initd" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ranging",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "Cisco-IOS-XE-docsis-oper:docsis-oper-data/cm-summary-total",
     "select": [
      [
       { "params": [ "initrc" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Offline",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "Cisco-IOS-XE-docsis-oper:docsis-oper-data/cm-summary-total",
     "select": [
      [
       { "params": [ "offline" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Partial Mode",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "Cisco-IOS-XE-docsis-oper:docsis-oper-data/cm-summary-total",
     "query": "SELECT sum(count) FROM (SELECT count(distinct(\"state\")) FROM \"Cisco-IOS-XE-docsis-oper:docsis-oper-data/cable-modem\" WHERE (\"state\" = 'p-online-pt')  AND $timeFilter GROUP BY \"mac_address\")",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CM Status over Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XE-docsis-oper:docsis-oper-data/cm-summary-total",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Registered",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XE-docsis-oper:docsis-oper-data/cm-summary-total",
     "select": [
      [
       { "params": [ "registered" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Wideband",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XE-docsis-oper:docsis-oper-data/cm-summary-total",
     "select": [
      [
       { "params": [ "wideband" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Initializing",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XE-docsis-oper:docsis-oper-data/cm-summary-total",
     "query": "SELECT mean(\"initd\") + mean(\"initio\") + mean(\"inito\") + mean(\"initrc\") FROM \"Cisco-IOS-XE-docsis-oper:docsis-oper-data/cm-summary-total\" WHERE\n $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "initd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$cBR8$/" }
     ]
    },
    {
     "alias": "Offline",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XE-docsis-oper:docsis-oper-data/cm-summary-total",
     "select": [
      [
       { "params": [ "offline" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Summary by cBR8",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "alias": "[[tag_source]]",
     "groupBy": [
      { "params": [ "source" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XE-docsis-oper:docsis-oper-data/cm-summary-total",
     "query": "SELECT last(\"total\") AS \"Total\", last(\"registered\") AS \"Registered\", last(\"wideband\") AS \"Wideband\", last(\"initd\") + last(\"inito\") + last(\"initio\") + last(\"initrc\") AS \"Initializing\", last(\"offline\") AS \"Offline\" FROM \"Cisco-IOS-XE-docsis-oper:docsis-oper-data/cm-summary-total\" WHERE $timeFilter GROUP BY \"source\"",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Total" ], "type": "alias" }
      ],
      [
       { "params": [ "registered" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Registered" ], "type": "alias" }
      ],
      [
       { "params": [ "wideband" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Wideband" ], "type": "alias" }
      ],
      [
       { "params": [ "initd" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Initializing" ], "type": "alias" }
      ],
      [
       { "params": [ "offline" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Offline" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "RPD Detail",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "id" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XE-docsis-oper:docsis-oper-data/cable-rpd-state",
     "select": [
      [
       { "params": [ "name" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "RPD Name" ], "type": "alias" }
      ],
      [
       { "params": [ "ip_addr" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "IP Address" ], "type": "alias" }
      ],
      [
       { "params": [ "state" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "State" ], "type": "alias" }
      ],
      [
       { "params": [ "clock_synced" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Clock Synced" ], "type": "alias" }
      ],
      [
       { "params": [ "core_role" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Core Role" ], "type": "alias" }
      ]
     ]
    }
   ]
  }
 ]
}