{
 "title": "cBR8 Detail",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "cBR8",
    "query": "SHOW TAG VALUES FROM \"Cisco-IOS-XE-docsis-oper:docsis-oper-data/cable-modem\" WITH KEY=\"source\""
   }
  ]
 },
 "panels": [
  { "title": "cBR8 Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XE-process-cpu-oper:cpu-usage/cpu-utilization",
     "query": "SELECT distinct(\"one_minute\") FROM \"Cisco-IOS-XE-process-cpu-oper:cpu-usage/cpu-utilization\" WHERE (\"source\" =~ /^$node$/) AND $timeFilter GROUP BY time($interval) fill(none)",
     "select": [
      [
       { "params": [ "one_minute" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Management Interface",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 1 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "alias": "OUT",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XE-interfaces-oper:interfaces/interface/statistics",
     "select": [
      [
       { "params": [ "tx_kbps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "10.90.148.205" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "GigabitEthernet0" }
     ]
    },
    {
     "alias": "IN",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XE-interfaces-oper:interfaces/interface/statistics",
     "select": [
      [
       { "params": [ "rx_kbps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "10.90.148.205" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "GigabitEthernet0" }
     ]
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "Cisco-IOS-XE-memory-oper:memory-statistics/memory-statistic",
     "query": "SELECT last(\"used_memory\") /last(\"total_memory\") * 100 FROM \"Cisco-IOS-XE-memory-oper:memory-statistics/memory-statistic\" WHERE (\"source\" =~ /^$node$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "used_memory" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "total_memory" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "WAN Interfaces",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "alias": "[[tag_name]] OUT",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XE-interfaces-oper:interfaces/interface/statistics",
     "query": "SELECT distinct(\"tx_kbps\") FROM \"Cisco-IOS-XE-interfaces-oper:interfaces/interface/statistics\" WHERE (\"source\" =~ /^$node$/ AND \"name\" =~ /^TenGigabitEthernet[45].*$/) AND $timeFilter GROUP BY time($__interval), \"name\" fill(none)",
     "select": [
      [
       { "params": [ "tx_kbps" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$cBR8$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "TenGigabitEthernet4/1/0" }
     ]
    },
    {
     "alias": "[[tag_name]] IN",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XE-interfaces-oper:interfaces/interface/statistics",
     "query": "SELECT distinct(\"rx_kbps\") FROM \"Cisco-IOS-XE-interfaces-oper:interfaces/interface/statistics\" WHERE (\"source\" =~ /^$node$/ AND \"name\" =~ /^TenGigabitEthernet[45].*$/) AND $timeFilter GROUP BY time($__interval), \"name\" fill(none)",
     "select": [
      [
       { "params": [ "rx_kbps" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$cBR8$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "TenGigabitEthernet4/1/0" }
     ]
    }
   ]
  },
  {
   "title": "WAN Interfaces Drops and Errors",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 9 },
   "targets": [
    {
     "alias": "Input CRC Errors",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XE-interfaces-oper:interfaces/interface/statistics",
     "query": "SELECT last(\"in_crc_errors\") FROM \"Cisco-IOS-XE-interfaces-oper:interfaces/interface/statistics\" WHERE (\"source\" =~ /^$node$/ AND \"name\" =~ /^TenGigabitEthernet[0123456789].*$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "in_crc_errors" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "Input Discards",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XE-interfaces-oper:interfaces/interface/statistics",
     "query": "SELECT last(\"in_discards\") FROM \"Cisco-IOS-XE-interfaces-oper:interfaces/interface/statistics\" WHERE (\"source\" =~ /^$node$/ AND \"name\" =~ /^TenGigabitEthernet[0123456789].*$/)  AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "in_discards" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "Input Errors",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XE-interfaces-oper:interfaces/interface/statistics",
     "query": "SELECT last(\"in_errors\") FROM \"Cisco-IOS-XE-interfaces-oper:interfaces/interface/statistics\" WHERE (\"source\" =~ /^$node$/ AND \"name\" =~ /^TenGigabitEthernet[0123456789].*$/)  AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "in_errors" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "Output Errors",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XR-infra-statsd-oper:infra-statistics/interfaces/interface/latest/generic-counters",
     "query": "SELECT last(\"out_errors\") FROM \"Cisco-IOS-XE-interfaces-oper:interfaces/interface/statistics\" WHERE (\"source\" =~ /^$node$/ AND \"name\" =~ /^TenGigabitEthernet[0123456789].*$/)  AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "output_errors" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "Output Discards",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XR-infra-statsd-oper:infra-statistics/interfaces/interface/latest/generic-counters",
     "query": "SELECT last(\"out_discards\") FROM \"Cisco-IOS-XE-interfaces-oper:interfaces/interface/statistics\" WHERE (\"source\" =~ /^$node$/ AND \"name\" =~ /^TenGigabitEthernet[0123456789].*$/)  AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "input_queue_drops" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "Flaps",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XR-infra-statsd-oper:infra-statistics/interfaces/interface/latest/generic-counters",
     "query": "SELECT last(\"num_flaps\") FROM \"Cisco-IOS-XE-interfaces-oper:interfaces/interface/statistics\" WHERE (\"source\" =~ /^$node$/ AND \"name\" =~ /^TenGigabitEthernet[0123456789].*$/)  AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "output_queue_drops" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    }
   ]
  },
  { "title": "Cable Modem Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "Cisco-IOS-XE-docsis-oper:docsis-oper-data/cm-summary-total",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Registered",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "Cisco-IOS-XE-docsis-oper:docsis-oper-data/cm-summary-total",
     "select": [
      [
       { "params": [ "registered" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Wideband",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "Cisco-IOS-XE-docsis-oper:docsis-oper-data/cm-summary-total",
     "select": [
      [
       { "params": [ "wideband" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "TFTP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "Cisco-IOS-XE-docsis-oper:docsis-oper-data/cm-summary-total",
     "select": [
      [
       { "params": [ "inito" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "DHCP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "Cisco-IOS-XE-docsis-oper:docsis-oper-data/cm-summary-total",
     "select": [
      [
       { "params": [ "initd" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Ranging",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "Cisco-IOS-XE-docsis-oper:docsis-oper-data/cm-summary-total",
     "query": "SELECT last(\"initrc\") FROM \"Cisco-IOS-XE-docsis-oper:docsis-oper-data/cable-modem\" WHERE (\"source\" = '10.90.148.205') AND $timeFilter",
     "select": [
      [
       { "params": [ "initrc" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Offline",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "Cisco-IOS-XE-docsis-oper:docsis-oper-data/cm-summary-total",
     "query": "SELECT last(\"offline\") FROM \"Cisco-IOS-XE-docsis-oper:docsis-oper-data/cm-summary-total\" WHERE (\"source\" =~ /^$cBR8$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "offline" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Partial Online",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "Cisco-IOS-XE-docsis-oper:docsis-oper-data/cm-summary-total",
     "query": "SELECT sum(count) FROM (SELECT count(distinct(\"state\")) FROM \"Cisco-IOS-XE-docsis-oper:docsis-oper-data/cable-modem\" WHERE (\"state\" = 'p-online-pt') and (\"source\" =~ /^$node$/) AND $timeFilter GROUP BY \"mac_address\")",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$cBR8$/" }
     ]
    }
   ]
  },
  {
   "title": "CM Status over Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XE-docsis-oper:docsis-oper-data/cm-summary-total",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "Registered",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XE-docsis-oper:docsis-oper-data/cm-summary-total",
     "select": [
      [
       { "params": [ "registered" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "Wideband",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XE-docsis-oper:docsis-oper-data/cm-summary-total",
     "select": [
      [
       { "params": [ "wideband" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "Initializing",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XE-docsis-oper:docsis-oper-data/cm-summary-total",
     "query": "SELECT last(\"initd\") + last(\"initio\") + last(\"inito\") + last(\"initrc\") FROM \"Cisco-IOS-XE-docsis-oper:docsis-oper-data/cm-summary-total\" WHERE (\"source\" =~ /^$node$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "initd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$cBR8$/" }
     ]
    },
    {
     "alias": "Offline",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XE-docsis-oper:docsis-oper-data/cm-summary-total",
     "select": [
      [
       { "params": [ "offline" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Status by Service Group",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "alias": "[[tag_cm_if_summary_totals/interface]] Online",
     "groupBy": [
      { "params": [ "cm_if_summary_totals/interface" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XE-docsis-oper:docsis-oper-data/cm-summary-total",
     "query": "SELECT last(\"cm_if_summary_totals/total\") AS \"Total\", last(\"cm_if_summary_totals/registered\") AS \"Registered\", last(\"cm_if_summary_totals/wideband\") AS \"Wideband\", last(\"cm_if_summary_totals/initd\") +  last(\"cm_if_summary_totals/initrc\") + last(\"cm_if_summary_totals/inito\") + last(\"cm_if_summary_totals/initio\") AS \"Initializing\", last(\"cm_if_summary_totals/offline\") AS \"Offline\" FROM \"Cisco-IOS-XE-docsis-oper:docsis-oper-data/cm-summary-total\" WHERE (\"source\" =~ /^$cBR8$/) AND $timeFilter GROUP BY \"cm_if_summary_totals/interface\"",
     "select": [
      [
       { "params": [ "cm_if_summary_totals/total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Total" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "cm_if_summary_totals/registered"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Registered" ], "type": "alias" }
      ],
      [
       { "params": [ "cm_if_summary_totals/wideband" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Wideband" ], "type": "alias" }
      ],
      [
       { "params": [ "cm_if_summary_totals/inito" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "init(o)" ], "type": "alias" }
      ],
      [
       { "params": [ "cm_if_summary_totals/initio" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "init(io)" ], "type": "alias" }
      ],
      [
       { "params": [ "cm_if_summary_totals/initd" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "init(d)" ], "type": "alias" }
      ],
      [
       { "params": [ "cm_if_summary_totals/initrc" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "init(rc)" ], "type": "alias" }
      ],
      [
       { "params": [ "cm_if_summary_totals/offline" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "offline" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "cm_if_summary_totals/unregistered"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Unregistered" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Remote PHY Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "DPIC Interfaces",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "Kbits" }
     ],
     "targets": [
      {
       "alias": "[[tag_name]] transmit",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Cisco-IOS-XE-interfaces-oper:interfaces/interface/statistics",
       "query": "SELECT distinct(\"tx_kbps\") FROM \"Cisco-IOS-XE-interfaces-oper:interfaces/interface/statistics\" WHERE (\"source\" =~ /^$node$/ AND \"name\" =~ /^TenGigabitEthernet[01236789].*$/) AND $timeFilter GROUP BY time($__interval), \"name\" fill(none)",
       "select": [
        [
         { "params": [ "tx_kbps" ], "type": "field" },
         {
          "params": [],
          "type": "distinct"
         }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=~", "value": "/^$cBR8$/" },
        { "condition": "AND", "key": "name", "operator": "=", "value": "TenGigabitEthernet4/1/0" }
       ]
      },
      {
       "alias": "[[tag_name]] receive",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Cisco-IOS-XE-interfaces-oper:interfaces/interface/statistics",
       "query": "SELECT distinct(\"rx_kbps\") FROM \"Cisco-IOS-XE-interfaces-oper:interfaces/interface/statistics\" WHERE (\"source\" =~ /^$node$/ AND \"name\" =~ /^TenGigabitEthernet[01236789].*$/) AND $timeFilter GROUP BY time($__interval), \"name\" fill(none)",
       "select": [
        [
         { "params": [ "rx_kbps" ], "type": "field" },
         {
          "params": [],
          "type": "distinct"
         }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=~", "value": "/^$cBR8$/" },
        { "condition": "AND", "key": "name", "operator": "=", "value": "TenGigabitEthernet4/1/0" }
       ]
      }
     ]
    },
    {
     "title": "RPD Detail",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 53 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "id" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XE-docsis-oper:docsis-oper-data/cable-rpd-state",
       "select": [
        [
         { "params": [ "name" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "RPD Name" ], "type": "alias" }
        ],
        [
         { "params": [ "ip_addr" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "IP Address" ], "type": "alias" }
        ],
        [
         { "params": [ "state" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "State" ], "type": "alias" }
        ],
        [
         { "params": [ "clock_synced" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Clock Synced" ], "type": "alias" }
        ],
        [
         { "params": [ "core_role" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Core Role" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=~", "value": "/^$node$/" }
       ]
      }
     ]
    }
   ]
  },
  { "title": "cBR Modem Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Cable Modem State",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "alias": "[[tag_mac_address]]",
     "groupBy": [
      { "params": [ "mac_address" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XE-docsis-oper:docsis-oper-data/cable-modem",
     "select": [
      [
       { "params": [ "state" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "State" ], "type": "alias" }
      ],
      [
       { "params": [ "interface" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Cable Interface" ], "type": "alias" }
      ],
      [
       { "params": [ "ipv4_addr" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "IPv4 Address" ], "type": "alias" }
      ],
      [
       { "params": [ "docsis_version" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "DOCSIS Version" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  { "title": "IGP Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Neighbors Interfaces",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "alias": "Neighbor Interface",
     "measurement": "Cisco-IOS-XE-ospf-oper:ospf-oper-data/ospf-state",
     "select": [
      [
       {
        "params": [
         "ospf_instance/ospf_area/ospf_interface/name"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Interface" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "ospf_instance/ospf_area/ospf_interface/ospf_neighbor/state"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "State" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "ospf_instance/ospf_area/ospf_interface/cost"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Cost" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "ospf_instance/ospf_area/ospf_interface/network_type"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Type" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  }
 ]
}