{
 "title": "cBR8 Summary",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "cBR8",
    "query": "SHOW TAG VALUES FROM \"Cisco-IOS-XE-docsis-oper:docsis-oper-data/cable-modem\" WITH KEY=\"source\""
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XE-process-cpu-oper:cpu-usage/cpu-utilization",
     "select": [
      [
       { "params": [ "one_minute" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$cBR8$/" }
     ]
    }
   ]
  },
  {
   "title": "Test SNMP Panel",
   "type": "table",
   "gridPos": { "h": 5, "w": 21, "x": 3, "y": 0 },
   "targets": [
    {
     "measurement": "CMTS-SNMPv2-MIB",
     "select": [
      [
       { "params": [ "sysDescr.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$cBR8$/" }
     ]
    }
   ]
  },
  { "title": "Cable Modem Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "Cisco-IOS-XE-docsis-oper:docsis-oper-data/cm-summary-total",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$cBR8$/" }
     ]
    }
   ]
  },
  {
   "title": "Registered",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "Cisco-IOS-XE-docsis-oper:docsis-oper-data/cm-summary-total",
     "select": [
      [
       { "params": [ "registered" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$cBR8$/" }
     ]
    }
   ]
  },
  {
   "title": "Wideband",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "Cisco-IOS-XE-docsis-oper:docsis-oper-data/cm-summary-total",
     "select": [
      [
       { "params": [ "wideband" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$cBR8$/" }
     ]
    }
   ]
  },
  {
   "title": "TFTP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "Cisco-IOS-XE-docsis-oper:docsis-oper-data/cm-summary-total",
     "select": [
      [
       { "params": [ "inito" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$cBR8$/" }
     ]
    }
   ]
  },
  {
   "title": "DHCP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "Cisco-IOS-XE-docsis-oper:docsis-oper-data/cm-summary-total",
     "select": [
      [
       { "params": [ "initd" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$cBR8$/" }
     ]
    }
   ]
  },
  {
   "title": "Ranging",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "Cisco-IOS-XE-docsis-oper:docsis-oper-data/cm-summary-total",
     "query": "SELECT last(\"initrc\") FROM \"Cisco-IOS-XE-docsis-oper:docsis-oper-data/cable-modem\" WHERE (\"source\" = '10.90.148.205') AND $timeFilter",
     "select": [
      [
       { "params": [ "initrc" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$cBR8$/" }
     ]
    }
   ]
  },
  {
   "title": "Offline",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "Cisco-IOS-XE-docsis-oper:docsis-oper-data/cm-summary-total",
     "query": "SELECT last(\"offline\") FROM \"Cisco-IOS-XE-docsis-oper:docsis-oper-data/cm-summary-total\" WHERE (\"source\" =~ /^$cBR8$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "offline" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$cBR8$/" }
     ]
    }
   ]
  },
  {
   "title": "Partial Online",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "Cisco-IOS-XE-docsis-oper:docsis-oper-data/cm-summary-total",
     "query": "SELECT sum(count) FROM (SELECT count(distinct(\"state\")) FROM \"Cisco-IOS-XE-docsis-oper:docsis-oper-data/cable-modem\" WHERE (\"state\" = 'p-online-pt') and (\"source\" =~ /^$cBR8$/) AND $timeFilter GROUP BY \"mac_address\")",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$cBR8$/" }
     ]
    }
   ]
  },
  {
   "title": "CM Status over Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XE-docsis-oper:docsis-oper-data/cm-summary-total",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$cBR8$/" }
     ]
    },
    {
     "alias": "Registered",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XE-docsis-oper:docsis-oper-data/cm-summary-total",
     "select": [
      [
       { "params": [ "registered" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$cBR8$/" }
     ]
    },
    {
     "alias": "Wideband",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XE-docsis-oper:docsis-oper-data/cm-summary-total",
     "select": [
      [
       { "params": [ "wideband" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$cBR8$/" }
     ]
    },
    {
     "alias": "Initializing",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XE-docsis-oper:docsis-oper-data/cm-summary-total",
     "query": "SELECT mean(\"initd\") + mean(\"initio\") + mean(\"inito\") + mean(\"initrc\") FROM \"Cisco-IOS-XE-docsis-oper:docsis-oper-data/cm-summary-total\" WHERE (\"source\" =~ /^$cBR8$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "initd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$cBR8$/" }
     ]
    },
    {
     "alias": "Offline",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XE-docsis-oper:docsis-oper-data/cm-summary-total",
     "select": [
      [
       { "params": [ "offline" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$cBR8$/" }
     ]
    }
   ]
  },
  {
   "title": "Status by Service Group",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "alias": "[[tag_cm_if_summary_totals/interface]] Online",
     "groupBy": [
      { "params": [ "cm_if_summary_totals/interface" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XE-docsis-oper:docsis-oper-data/cm-summary-total",
     "query": "SELECT last(\"cm_if_summary_totals/total\") AS \"Total\", last(\"cm_if_summary_totals/registered\") AS \"Registered\", last(\"cm_if_summary_totals/wideband\") AS \"Wideband\", last(\"cm_if_summary_totals/initd\") +  last(\"cm_if_summary_totals/initrc\") + last(\"cm_if_summary_totals/inito\") + last(\"cm_if_summary_totals/initio\") AS \"Initializing\", last(\"cm_if_summary_totals/offline\") AS \"Offline\" FROM \"Cisco-IOS-XE-docsis-oper:docsis-oper-data/cm-summary-total\" WHERE (\"source\" =~ /^$cBR8$/) AND $timeFilter GROUP BY \"cm_if_summary_totals/interface\"",
     "select": [
      [
       { "params": [ "cm_if_summary_totals/total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Total" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "cm_if_summary_totals/registered"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Registered" ], "type": "alias" }
      ],
      [
       { "params": [ "cm_if_summary_totals/wideband" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Wideband" ], "type": "alias" }
      ],
      [
       { "params": [ "cm_if_summary_totals/inito" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "init(o)" ], "type": "alias" }
      ],
      [
       { "params": [ "cm_if_summary_totals/initio" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "init(io)" ], "type": "alias" }
      ],
      [
       { "params": [ "cm_if_summary_totals/initd" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "init(d)" ], "type": "alias" }
      ],
      [
       { "params": [ "cm_if_summary_totals/initrc" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "init(rc)" ], "type": "alias" }
      ],
      [
       { "params": [ "cm_if_summary_totals/offline" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "offline" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "cm_if_summary_totals/unregistered"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Unregistered" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$cBR8$/" }
     ]
    }
   ]
  },
  { "title": "cBR Modem Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Partial Online Modems",
   "type": "table",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 26 },
   "targets": [
    {
     "alias": "[[tag_mac_address]]",
     "groupBy": [
      { "params": [ "mac_address" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XE-docsis-oper:docsis-oper-data/cable-modem",
     "query": "SELECT last(\"state\") AS \"State\", last(\"interface\") AS \"Cable Interface\", last(\"ipv4_addr\") AS \"IPv4 Address\", last(\"docsis_version\") AS \"DOCSIS Version\" FROM \"Cisco-IOS-XE-docsis-oper:docsis-oper-data/cable-modem\" WHERE (\"source\" =~ /^$cBR8$/) AND (\"state\" = 'p-online-pt') AND $timeFilter GROUP BY \"mac_address\"",
     "select": [
      [
       { "params": [ "state" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "State" ], "type": "alias" }
      ],
      [
       { "params": [ "interface" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Cable Interface" ], "type": "alias" }
      ],
      [
       { "params": [ "ipv4_addr" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "IPv4 Address" ], "type": "alias" }
      ],
      [
       { "params": [ "docsis_version" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "DOCSIS Version" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$cBR8$/" }
     ]
    }
   ]
  },
  {
   "title": "Cable Modem State",
   "type": "table",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 31 },
   "targets": [
    {
     "alias": "[[tag_mac_address]]",
     "groupBy": [
      { "params": [ "mac_address" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XE-docsis-oper:docsis-oper-data/cable-modem",
     "select": [
      [
       { "params": [ "state" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "State" ], "type": "alias" }
      ],
      [
       { "params": [ "interface" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Cable Interface" ], "type": "alias" }
      ],
      [
       { "params": [ "ipv4_addr" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "IPv4 Address" ], "type": "alias" }
      ],
      [
       { "params": [ "docsis_version" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "DOCSIS Version" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$cBR8$/" }
     ]
    }
   ]
  }
 ]
}