{
 "title": "Service Group Detail",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "cBR8",
    "query": "SHOW TAG VALUES FROM \"Cisco-IOS-XE-docsis-oper:docsis-oper-data/cable-modem\" WITH KEY=\"source\""
   },
   {
    "name": "sg",
    "label": "Cable Interface",
    "query": "show tag values from \"Cisco-IOS-XE-docsis-oper:docsis-oper-data/cm-summary-total\" with key=\"cm_if_summary_totals/interface\""
   }
  ]
 },
 "panels": [
  { "title": "Cable Modem Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "Cisco-IOS-XE-docsis-oper:docsis-oper-data/cm-summary-total",
     "select": [
      [
       { "params": [ "cm_if_summary_totals/total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$node$/" },
      { "condition": "AND", "key": "cm_if_summary_totals/interface", "operator": "=~", "value": "/^$sg$/" }
     ]
    }
   ]
  },
  {
   "title": "Registered",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "Cisco-IOS-XE-docsis-oper:docsis-oper-data/cm-summary-total",
     "select": [
      [
       {
        "params": [
         "cm_if_summary_totals/registered"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$node$/" },
      { "condition": "AND", "key": "cm_if_summary_totals/interface", "operator": "=~", "value": "/^$sg$/" }
     ]
    }
   ]
  },
  {
   "title": "Wideband",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "Cisco-IOS-XE-docsis-oper:docsis-oper-data/cm-summary-total",
     "select": [
      [
       { "params": [ "cm_if_summary_totals/wideband" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$node$/" },
      { "condition": "AND", "key": "cm_if_summary_totals/interface", "operator": "=~", "value": "/^$sg$/" }
     ]
    }
   ]
  },
  {
   "title": "TFTP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "Cisco-IOS-XE-docsis-oper:docsis-oper-data/cm-summary-total",
     "select": [
      [
       { "params": [ "cm_if_summary_totals/inito" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$node$/" },
      { "condition": "AND", "key": "cm_if_summary_totals/interface", "operator": "=~", "value": "/^$sg$/" }
     ]
    }
   ]
  },
  {
   "title": "DHCP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "Cisco-IOS-XE-docsis-oper:docsis-oper-data/cm-summary-total",
     "select": [
      [
       { "params": [ "cm_if_summary_totals/initd" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$node$/" },
      { "condition": "AND", "key": "cm_if_summary_totals/interface", "operator": "=~", "value": "/^$sg$/" }
     ]
    }
   ]
  },
  {
   "title": "Ranging",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "Cisco-IOS-XE-docsis-oper:docsis-oper-data/cm-summary-total",
     "query": "SELECT last(\"initrc\") FROM \"Cisco-IOS-XE-docsis-oper:docsis-oper-data/cable-modem\" WHERE (\"source\" = '10.90.148.205') AND $timeFilter",
     "select": [
      [
       { "params": [ "cm_if_summary_totals/initrc" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$node$/" },
      { "condition": "AND", "key": "cm_if_summary_totals/interface", "operator": "=~", "value": "/^$sg$/" }
     ]
    }
   ]
  },
  {
   "title": "Offline",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "Cisco-IOS-XE-docsis-oper:docsis-oper-data/cm-summary-total",
     "query": "SELECT last(\"offline\") FROM \"Cisco-IOS-XE-docsis-oper:docsis-oper-data/cm-summary-total\" WHERE (\"source\" =~ /^$cBR8$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "cm_if_summary_totals/offline" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$node$/" },
      { "condition": "AND", "key": "cm_if_summary_totals/interface", "operator": "=~", "value": "/^$sg$/" }
     ]
    }
   ]
  },
  {
   "title": "CM Status over Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XE-docsis-oper:docsis-oper-data/cm-summary-total",
     "select": [
      [
       { "params": [ "cm_if_summary_totals/total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$node$/" },
      { "condition": "AND", "key": "cm_if_summary_totals/interface", "operator": "=~", "value": "/^$sg$/" }
     ]
    },
    {
     "alias": "Registered",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XE-docsis-oper:docsis-oper-data/cm-summary-total",
     "select": [
      [
       {
        "params": [
         "cm_if_summary_totals/registered"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$node$/" },
      { "condition": "AND", "key": "cm_if_summary_totals/interface", "operator": "=~", "value": "/^$sg$/" }
     ]
    },
    {
     "alias": "Wideband",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XE-docsis-oper:docsis-oper-data/cm-summary-total",
     "select": [
      [
       { "params": [ "cm_if_summary_totals/wideband" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$node$/" },
      { "condition": "AND", "key": "cm_if_summary_totals/interface", "operator": "=~", "value": "/^$sg$/" }
     ]
    },
    {
     "alias": "Initializing",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XE-docsis-oper:docsis-oper-data/cm-summary-total",
     "query": "SELECT last(\"cm_if_summary_totals/initd\"), last(\"cm_if_summary_totals/initio\"), last(\"cm_if_summary_totals/inito\"), last(\"cm_if_summary_totals/initrc\") FROM \"Cisco-IOS-XE-docsis-oper:docsis-oper-data/cm-summary-total\" WHERE (\"source\" =~ /^$node$/ AND \"cm_if_summary_totals/interface\" =~ /^$sg$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "cm_if_summary_totals/initd" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "cm_if_summary_totals/initio" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "cm_if_summary_totals/inito" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "cm_if_summary_totals/initrc" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$node$/" },
      { "condition": "AND", "key": "cm_if_summary_totals/interface", "operator": "=~", "value": "/^$sg$/" }
     ]
    },
    {
     "alias": "Offline",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XE-docsis-oper:docsis-oper-data/cm-summary-total",
     "select": [
      [
       { "params": [ "cm_if_summary_totals/offline" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$node$/" },
      { "condition": "AND", "key": "cm_if_summary_totals/interface", "operator": "=~", "value": "/^$sg$/" }
     ]
    }
   ]
  }
 ]
}