apiVersion: 1

deleteDatasources:
  - name: MYINFLUX
    orgId: 1

datasources:
- name: InfluxDB-SNMP
  type: influxdb
  access: proxy
  url: http://influxdb:8086
  password: 
  user: snmp
  database: snmp
  basicAuth: false
  basicAuthUser:
  basicAuthPassword:
  withCredentials:
  isDefault: false
  jsonData:
     tlsAuth: false
     tlsAuthWithCACert: false
  secureJsonData:
    tlsCACert: ""
    tlsClientCert: ""
    tlsClientKey: ""
  version: 1
  editable: true