{
 "title": "Device_Health_Check_Demo",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": "SHOW TAG VALUES FROM \"Cisco-IOS-XR-shellutil-oper:system-time/uptime\" WITH KEY=source"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilization",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "CPU",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XR-wdsysmon-fd-oper:system-monitoring/cpu-utilization",
     "query": "SELECT max(\"total-cpu-one-minute\") FROM \"sysmon\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "total_cpu_one_minute" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Use Percent",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "Memory Use",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oper",
     "query": "SELECT last(\"system_ram_memory\") - last(\"free_application_memory\") FROM \"oper\" WHERE (\"source\" =~ /^$Node$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "system_ram_memory" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "-" ], "type": "math" }
      ],
      [
       { "params": [ "free_application_memory" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "alias": "Memory Use",
     "measurement": "Cisco-IOS-XR-shellutil-oper:system-time/uptime",
     "query": "SELECT \"uptime\" FROM \"shellutil-oper\" WHERE (\"source\" =~ /^$Node$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    }
   ]
  },
  {
   "title": "Interface Summary",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "alias": "Total Interfaces",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XR-pfi-im-cmd-oper:interfaces/interface-summary",
     "query": "SELECT last(\"interface-counts__interface-count\") FROM \"Cisco-IOS-XR-pfi-im-cmd-oper:interfaces/interface-summary\" WHERE (\"Producer\" =~ /^$Node$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "interface_counts/interface_count"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "Interfaces Up",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XR-pfi-im-cmd-oper:interfaces/interface-summary",
     "select": [
      [
       {
        "params": [
         "interface_counts/up_interface_count"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "Interfaces Down",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XR-pfi-im-cmd-oper:interfaces/interface-summary",
     "select": [
      [
       {
        "params": [
         "interface_counts/down_interface_count"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "Interfaces Admin Down",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XR-pfi-im-cmd-oper:interfaces/interface-summary",
     "select": [
      [
       {
        "params": [
         "interface_counts/admin_down_interface_count"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    }
   ]
  },
  {
   "title": "Device Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "[[tag_interface_name]] IN",
     "groupBy": [
      { "params": [ "interface_name" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-infra-statsd-oper:infra-statistics/interfaces/interface/latest/generic-counters",
     "query": "SELECT non_negative_derivative(\"bytes-received\", 1s) *8 FROM \"Cisco-IOS-XR-infra-statsd-oper:infra-statistics/interfaces/interface/latest/generic-counters\" WHERE (\"Producer\" =~ /^$Node$/) AND $timeFilter GROUP BY \"interface-name\"",
     "select": [
      [
       { "params": [ "bytes_received" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "[[tag_interface_name]] OUT",
     "groupBy": [
      { "params": [ "interface_name" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-infra-statsd-oper:infra-statistics/interfaces/interface/latest/generic-counters",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    }
   ]
  },
  {
   "title": "Device Drops and Errors",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "alias": "Input Drops",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XR-infra-statsd-oper:infra-statistics/interfaces/interface/latest/generic-counters",
     "select": [
      [
       { "params": [ "input_drops" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "Output Drops",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XR-infra-statsd-oper:infra-statistics/interfaces/interface/latest/generic-counters",
     "select": [
      [
       { "params": [ "output_drops" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "Input Errors",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XR-infra-statsd-oper:infra-statistics/interfaces/interface/latest/generic-counters",
     "select": [
      [
       { "params": [ "input_errors" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "PE2-Node115" }
     ]
    },
    {
     "alias": "Output Errors",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XR-infra-statsd-oper:infra-statistics/interfaces/interface/latest/generic-counters",
     "query": "SELECT last(\"output_errors\") FROM \"ifstats\" WHERE (\"source\" =~ /^$Node$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "output_errors" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "Input Queue Drops",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XR-infra-statsd-oper:infra-statistics/interfaces/interface/latest/generic-counters",
     "query": "SELECT last(\"input-queue-drops\") FROM \"Cisco-IOS-XR-infra-statsd-oper:infra-statistics/interfaces/interface/latest/generic-counters\" WHERE (\"Producer\" =~ /^$Node$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "input_queue_drops" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "Output Queue Drops",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XR-infra-statsd-oper:infra-statistics/interfaces/interface/latest/generic-counters",
     "select": [
      [
       { "params": [ "output_queue_drops" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    }
   ]
  },
  {
   "title": "Optical parameters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Power levels",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "dB" }
     ],
     "targets": [
      {
       "alias": "[[tag_name]].[[tag_lane-data_lane-index]] RX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "lane-data__lane-index" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-controller-optics-oper:optics-oper/optics-ports/optics-port/optics-info",
       "query": "SELECT distinct(\"lane-data__receive-power\")  / 100 FROM \"Cisco-IOS-XR-controller-optics-oper:optics-oper/optics-ports/optics-port/optics-info\" WHERE (\"Producer\" =~ /^$Node$/) AND $timeFilter GROUP BY time($__interval), \"name\", \"lane-data__lane-index\"",
       "select": [
        [
         { "params": [ "lane_data/receive_power" ], "type": "field" },
         {
          "params": [],
          "type": "distinct"
         },
         { "params": [ " / 100" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "[[tag_name]].[[tag_lane-data__lane-index]] TX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "lane-data__lane-index" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-controller-optics-oper:optics-oper/optics-ports/optics-port/optics-info",
       "select": [
        [
         { "params": [ "lane_data/transmit_power" ], "type": "field" },
         {
          "params": [],
          "type": "distinct"
         },
         { "params": [ " / 100" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=~", "value": "/^$Node$/" }
       ]
      }
     ]
    },
    {
     "title": "Laser Bias Current",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "amp" }
     ],
     "targets": [
      {
       "alias": "[[tag_name]].[[tag_lane-data__lane-index]] RX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "lane-data__lane-index" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-controller-optics-oper:optics-oper/optics-ports/optics-port/optics-info",
       "select": [
        [
         {
          "params": [
           "lane_data/laser_bias_current_milli_amps"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "distinct"
         },
         { "params": [ " / 100" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=~", "value": "/^$Node$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "ISIS Routing Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "ISIS Route Summary",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "Active IPv4 Routes Count",
       "measurement": "Cisco-IOS-XR-ip-rib-ipv4-oper:rib/vrfs/vrf/afs/af/safs/saf/ip-rib-route-table-names/ip-rib-route-table-name/protocol/isis/as/information",
       "query": "SELECT \"active-routes-count\" FROM \"Cisco-IOS-XR-ip-rib-ipv4-oper:rib/vrfs/vrf/afs/af/safs/saf/ip-rib-route-table-names/ip-rib-route-table-name/protocol/isis/as/information\" WHERE (\"Producer\" =~ /^$Node$/ AND \"af-name\" = 'IPv4' AND \"saf-name\" = 'Unicast') AND $timeFilter",
       "select": [
        [
         { "params": [ "active_routes_count" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=~", "value": "/^$Node$/" },
        { "condition": "AND", "key": "af_name", "operator": "=", "value": "IPv4" },
        { "condition": "AND", "key": "saf_name", "operator": "=", "value": "Unicast" }
       ]
      },
      {
       "alias": "Backup IPv4 Routes Count",
       "measurement": "Cisco-IOS-XR-ip-rib-ipv4-oper:rib/vrfs/vrf/afs/af/safs/saf/ip-rib-route-table-names/ip-rib-route-table-name/protocol/isis/as/information",
       "query": "SELECT \"backup-routes-count\" FROM \"Cisco-IOS-XR-ip-rib-ipv4-oper:rib/vrfs/vrf/afs/af/safs/saf/ip-rib-route-table-names/ip-rib-route-table-name/protocol/isis/as/information\" WHERE (\"Producer\" =~ /^$Node$/ AND \"af-name\" = 'IPv4' AND \"saf-name\" = 'Unicast') AND $timeFilter",
       "select": [
        [
         { "params": [ "backup_routes_count" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=~", "value": "/^$Node$/" },
        { "condition": "AND", "key": "af_name", "operator": "=", "value": "IPv4" },
        { "condition": "AND", "key": "saf_name", "operator": "=", "value": "Unicast" }
       ]
      },
      {
       "alias": "Active IPv6 Routes Count",
       "measurement": "Cisco-IOS-XR-ip-rib-ipv4-oper:rib/vrfs/vrf/afs/af/safs/saf/ip-rib-route-table-names/ip-rib-route-table-name/protocol/isis/as/information",
       "query": "SELECT \"active_routes_count\" FROM \"rib-v6\" WHERE (\"source\" =~ /^$Node$/ AND \"saf_name\" = 'Unicast') AND $timeFilter",
       "select": [
        [
         { "params": [ "active_routes_count" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=~", "value": "/^$Node$/" },
        { "condition": "AND", "key": "saf_name", "operator": "=", "value": "Unicast" }
       ]
      },
      {
       "alias": "Backup IPv6 Routes Count",
       "measurement": "Cisco-IOS-XR-ip-rib-ipv6-oper:ipv6-rib/vrfs/vrf/afs/af/safs/saf/ip-rib-route-table-names/ip-rib-route-table-name/protocol/isis/as/information",
       "select": [
        [
         { "params": [ "backup-routes-count" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" },
        { "condition": "AND", "key": "saf-name", "operator": "=", "value": "Unicast" }
       ]
      }
     ]
    },
    {
     "title": "ISIS Route Change",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "Active IPv4 Routes count change",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rib-ipv4-oper:rib/vrfs/vrf/afs/af/safs/saf/ip-rib-route-table-names/ip-rib-route-table-name/protocol/isis/as/information",
       "select": [
        [
         { "params": [ "active_routes_count" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=~", "value": "/^$Node$/" },
        { "condition": "AND", "key": "af_name", "operator": "=", "value": "IPv4" },
        { "condition": "AND", "key": "saf_name", "operator": "=", "value": "Unicast" }
       ]
      },
      {
       "alias": "Backup IPv4 Routes count change",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rib-ipv4-oper:rib/vrfs/vrf/afs/af/safs/saf/ip-rib-route-table-names/ip-rib-route-table-name/protocol/isis/as/information",
       "select": [
        [
         { "params": [ "backup_routes_count" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=~", "value": "/^$Node$/" },
        { "condition": "AND", "key": "af_name", "operator": "=", "value": "IPv4" },
        { "condition": "AND", "key": "saf_name", "operator": "=", "value": "Unicast" }
       ]
      },
      {
       "alias": "Active IPv6 Routes count change",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rib-ipv6-oper:ipv6-rib/vrfs/vrf/afs/af/safs/saf/ip-rib-route-table-names/ip-rib-route-table-name/protocol/isis/as/information",
       "select": [
        [
         { "params": [ "active-routes-count" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=~", "value": "/^$Node$/" },
        { "condition": "AND", "key": "saf-name", "operator": "=", "value": "Unicast" }
       ]
      },
      {
       "alias": "Backup IPv6 Routes count change",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rib-ipv6-oper:ipv6-rib/vrfs/vrf/afs/af/safs/saf/ip-rib-route-table-names/ip-rib-route-table-name/protocol/isis/as/information",
       "select": [
        [
         { "params": [ "backup-routes-count" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=~", "value": "/^$Node$/" },
        { "condition": "AND", "key": "saf-name", "operator": "=", "value": "Unicast" }
       ]
      }
     ]
    },
    {
     "title": "Neighbors Interfaces",
     "type": "table-old",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 29 },
     "targets": [
      {
       "alias": "Neighbor Interface",
       "measurement": "Cisco-IOS-XR-clns-isis-oper:isis/instances/instance/levels/level/adjacencies/adjacency",
       "select": [
        [
         { "params": [ "adjacency_interface" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=~", "value": "/^$Node$/" }
       ]
      }
     ]
    },
    {
     "title": "Neighbor state",
     "type": "table-old",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 29 },
     "targets": [
      {
       "alias": "[[tag_system-id]]",
       "groupBy": [
        { "params": [ "system-id" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-clns-isis-oper:isis/instances/instance/levels/level/adjacencies/adjacency",
       "select": [
        [
         { "params": [ "adjacency_state" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=~", "value": "/^$Node$/" }
       ]
      }
     ]
    },
    {
     "title": "ISIS frames drops",
     "type": "table-old",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 29 },
     "targets": [
      {
       "alias": "IIH Drops",
       "measurement": "Cisco-IOS-XR-clns-isis-oper:isis/instances/instance/statistics-global",
       "query": "SELECT \"statistics__iih-dropped-count\" FROM \"Cisco-IOS-XR-clns-isis-oper:isis/instances/instance/statistics-global\" WHERE (\"Producer\" =~ /^$Node$/) AND $timeFilter",
       "select": [
        [
         { "params": [ "statistics/iih_dropped_count" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "LSP Drops",
       "measurement": "Cisco-IOS-XR-clns-isis-oper:isis/instances/instance/statistics-global",
       "select": [
        [
         { "params": [ "statistics/lsp_dropped_count" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "Invalid Checksum LSP",
       "measurement": "Cisco-IOS-XR-clns-isis-oper:isis/instances/instance/statistics-global",
       "select": [
        [
         {
          "params": [
           "statistics/invalid_checksum_lsp_count"
          ],
          "type": "field"
         }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=~", "value": "/^$Node$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "BGP Routing Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "BGP Path Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "BGP Path Count",
       "measurement": "Cisco-IOS-XR-ipv4-bgp-oper:bgp/instances/instance/instance-active/default-vrf/process-info",
       "query": "SELECT \"vrf__path-count\" FROM \"Cisco-IOS-XR-ipv4-bgp-oper:bgp/instances/instance/instance-active/default-vrf/process-info\" WHERE (\"Producer\" =~ /^$Node$/) AND $timeFilter",
       "select": [
        [
         { "params": [ "vrf/path_count" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=~", "value": "/^$Node$/" }
       ]
      }
     ]
    },
    {
     "title": "BGP Path Count Change",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "BGP Path Count Change",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Cisco-IOS-XR-ipv4-bgp-oper:bgp/instances/instance/instance-active/default-vrf/process-info",
       "query": "SELECT difference(last(\"vrf/path_count\")) FROM \"bgp-process\" WHERE (\"source\" = 'PE2-Node115') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "vrf/path_count" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=~", "value": "/^$Node$/" }
       ]
      }
     ]
    },
    {
     "title": "BGP Prefix Counts",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "BGP Prefix Counts",
       "measurement": "Cisco-IOS-XR-ipv4-bgp-oper:bgp/instances/instance/instance-active/default-vrf/process-info",
       "select": [
        [
         { "params": [ "vrf/network_count" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=~", "value": "/^$Node$/" }
       ]
      }
     ]
    },
    {
     "title": "BGP Prefix Counts Change",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "BGP Prefix Counts",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Cisco-IOS-XR-ipv4-bgp-oper:bgp/instances/instance/instance-active/default-vrf/process-info",
       "select": [
        [
         { "params": [ "vrf/network_count" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=~", "value": "/^$Node$/" }
       ]
      }
     ]
    },
    {
     "title": "BGP Neighbors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Established BGP Neighbor Count",
       "measurement": "Cisco-IOS-XR-ipv4-bgp-oper:bgp/instances/instance/instance-active/default-vrf/process-info",
       "select": [
        [
         {
          "params": [
           "global/established_neighbors_count_total"
          ],
          "type": "field"
         }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=~", "value": "/^$Node$/" }
       ]
      }
     ]
    },
    {
     "title": "BGP Neighbor Change",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Established BGP Neighbor Count",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Cisco-IOS-XR-ipv4-bgp-oper:bgp/instances/instance/instance-active/default-vrf/process-info",
       "select": [
        [
         {
          "params": [
           "global/established_neighbors_count_total"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "last"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=~", "value": "/^$Node$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "MPLS tunnels information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tunnels overview",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Auto-BW tunnels",
       "measurement": "optics",
       "query": "SELECT \"auto-bandwidth-tunnels\" FROM \"Cisco-IOS-XR-mpls-te-oper:mpls-te/tunnels/summary\" WHERE (\"Producer\" =~ /^$Node$/) AND $timeFilter",
       "select": [
        [
         { "params": [ "auto-bandwidth-tunnels" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "Backup tunnels",
       "measurement": "Cisco-IOS-XR-mpls-te-oper:mpls-te/tunnels/summary",
       "select": [
        [
         { "params": [ "backup-tunnels" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "Bandwidth protected tunnels",
       "measurement": "Cisco-IOS-XR-mpls-te-oper:mpls-te/tunnels/summary",
       "select": [
        [
         { "params": [ "bw-protected-tunnels" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "FRR-headend tunnels",
       "measurement": "Cisco-IOS-XR-mpls-te-oper:mpls-te/tunnels/summary",
       "select": [
        [
         { "params": [ "frr-head-tunnels" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "FRR-midpoint tunnels",
       "measurement": "Cisco-IOS-XR-mpls-te-oper:mpls-te/tunnels/summary",
       "select": [
        [
         { "params": [ "frr-mid-point-tunnels" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "FRR-protected tunnels",
       "measurement": "Cisco-IOS-XR-mpls-te-oper:mpls-te/tunnels/summary",
       "select": [
        [
         { "params": [ "frr-protected-interfaces" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "Link protected tunnels",
       "measurement": "Cisco-IOS-XR-mpls-te-oper:mpls-te/tunnels/summary",
       "select": [
        [
         { "params": [ "link-protected-tunnels" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "Node protected tunnels",
       "measurement": "Cisco-IOS-XR-mpls-te-oper:mpls-te/tunnels/summary",
       "select": [
        [
         { "params": [ "node-protected-tunnels" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "P2P headend tunnels",
       "measurement": "Cisco-IOS-XR-mpls-te-oper:mpls-te/tunnels/summary",
       "select": [
        [
         { "params": [ "p2p-head-tunnels" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "Protected headend tunnels",
       "measurement": "Cisco-IOS-XR-mpls-te-oper:mpls-te/tunnels/summary",
       "select": [
        [
         { "params": [ "protected-head-tunnels" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "Protected midpoint tunnels",
       "measurement": "Cisco-IOS-XR-mpls-te-oper:mpls-te/tunnels/summary",
       "select": [
        [
         { "params": [ "protected-mid-point-tunnels" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      }
     ]
    },
    {
     "title": "Tunnels bring up / down count",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Auto-BW tunnels change",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" }
       ],
       "measurement": "Cisco-IOS-XR-mpls-te-oper:mpls-te/tunnels/summary",
       "select": [
        [
         { "params": [ "auto-bandwidth-tunnels" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "Backup tunnels change",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" }
       ],
       "measurement": "Cisco-IOS-XR-mpls-te-oper:mpls-te/tunnels/summary",
       "select": [
        [
         { "params": [ "backup-tunnels" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "Bandwidth protected tunnels change",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" }
       ],
       "measurement": "Cisco-IOS-XR-mpls-te-oper:mpls-te/tunnels/summary",
       "select": [
        [
         { "params": [ "bw-protected-tunnels" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "FRR-headend tunnels change",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" }
       ],
       "measurement": "Cisco-IOS-XR-mpls-te-oper:mpls-te/tunnels/summary",
       "select": [
        [
         { "params": [ "frr-head-tunnels" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "FRR-midpoint tunnels change",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" }
       ],
       "measurement": "Cisco-IOS-XR-mpls-te-oper:mpls-te/tunnels/summary",
       "select": [
        [
         { "params": [ "frr-mid-point-tunnels" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "FRR-protected tunnels change",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" }
       ],
       "measurement": "Cisco-IOS-XR-mpls-te-oper:mpls-te/tunnels/summary",
       "select": [
        [
         { "params": [ "frr-protected-interfaces" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "Link protected tunnels change",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" }
       ],
       "measurement": "Cisco-IOS-XR-mpls-te-oper:mpls-te/tunnels/summary",
       "select": [
        [
         { "params": [ "link-protected-tunnels" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "Node protected tunnels change",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" }
       ],
       "measurement": "Cisco-IOS-XR-mpls-te-oper:mpls-te/tunnels/summary",
       "select": [
        [
         { "params": [ "node-protected-tunnels" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "P2P headend tunnels change",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" }
       ],
       "measurement": "Cisco-IOS-XR-mpls-te-oper:mpls-te/tunnels/summary",
       "select": [
        [
         { "params": [ "p2p-head-tunnels" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "Protected headend tunnels change",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" }
       ],
       "measurement": "Cisco-IOS-XR-mpls-te-oper:mpls-te/tunnels/summary",
       "select": [
        [
         { "params": [ "protected-head-tunnels" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "Protected midpoint tunnels change",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" }
       ],
       "measurement": "Cisco-IOS-XR-mpls-te-oper:mpls-te/tunnels/summary",
       "select": [
        [
         { "params": [ "protected-mid-point-tunnels" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      }
     ]
    },
    {
     "title": "RSVP allocation per interface overview",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "alias": "Consumed RSVP BW, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/interface-briefs/interface-brief",
       "query": "SELECT \"bandwidth-information__pre-standard-dste-interface__allocated-bit-rate\" FROM \"Cisco-IOS-XR-ip-rsvp-oper:rsvp/interface-briefs/interface-brief\" WHERE (\"Producer\" =~ /^$Node$/) AND $timeFilter GROUP BY \"interface-name\"",
       "select": [
        [
         {
          "params": [
           "bandwidth-information__pre-standard-dste-interface__allocated-bit-rate"
          ],
          "type": "field"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      }
     ]
    },
    {
     "title": "RSVP messages stats overview",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 68 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "Bundle RX ACK, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
       "select": [
        [
         { "params": [ "bundle-received-messages__ack" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "Bundle RX HELLO, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
       "query": "SELECT \"bundle-received-messages__hello\" FROM \"Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message\" WHERE \"Producer\" =~ /^$Node$/ AND \"interface-name\" =~ /Bundle.*/ AND $timeFilter GROUP BY \"interface-name\"",
       "select": [
        [
         {
          "params": [
           "bundle-received-messages__hello"
          ],
          "type": "field"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "Bundle RX PATH, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
       "query": "SELECT \"bundle-received-messages__hello\" FROM \"Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message\" WHERE \"Producer\" =~ /^$Node$/ AND \"interface-name\" =~ /Bundle.*/ AND $timeFilter GROUP BY \"interface-name\"",
       "select": [
        [
         { "params": [ "bundle-received-messages__path" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "Bundle RX PATH ERROR, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
       "query": "SELECT \"bundle-received-messages__hello\" FROM \"Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message\" WHERE \"Producer\" =~ /^$Node$/ AND \"interface-name\" =~ /Bundle.*/ AND $timeFilter GROUP BY \"interface-name\"",
       "select": [
        [
         {
          "params": [
           "bundle-received-messages__path-error"
          ],
          "type": "field"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "Bundle RX PATH TEAR, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
       "query": "SELECT \"bundle-received-messages__hello\" FROM \"Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message\" WHERE \"Producer\" =~ /^$Node$/ AND \"interface-name\" =~ /Bundle.*/ AND $timeFilter GROUP BY \"interface-name\"",
       "select": [
        [
         {
          "params": [
           "bundle-received-messages__path-tear"
          ],
          "type": "field"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "Bundle RX RESV, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
       "query": "SELECT \"bundle-received-messages__hello\" FROM \"Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message\" WHERE \"Producer\" =~ /^$Node$/ AND \"interface-name\" =~ /Bundle.*/ AND $timeFilter GROUP BY \"interface-name\"",
       "select": [
        [
         {
          "params": [
           "bundle-received-messages__reservation"
          ],
          "type": "field"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "Bundle RX RESV CONFIRM, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
       "query": "SELECT \"bundle-received-messages__hello\" FROM \"Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message\" WHERE \"Producer\" =~ /^$Node$/ AND \"interface-name\" =~ /Bundle.*/ AND $timeFilter GROUP BY \"interface-name\"",
       "select": [
        [
         {
          "params": [
           "bundle-received-messages__reservation-confirm"
          ],
          "type": "field"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "Bundle RX RESV ERROR, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
       "query": "SELECT \"bundle-received-messages__hello\" FROM \"Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message\" WHERE \"Producer\" =~ /^$Node$/ AND \"interface-name\" =~ /Bundle.*/ AND $timeFilter GROUP BY \"interface-name\"",
       "select": [
        [
         {
          "params": [
           "bundle-received-messages__reservation-error"
          ],
          "type": "field"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "Bundle RX RESV TEAR, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
       "query": "SELECT \"bundle-received-messages__hello\" FROM \"Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message\" WHERE \"Producer\" =~ /^$Node$/ AND \"interface-name\" =~ /Bundle.*/ AND $timeFilter GROUP BY \"interface-name\"",
       "select": [
        [
         {
          "params": [
           "bundle-received-messages__reservation-tear"
          ],
          "type": "field"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "Bundle TX ACK, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
       "select": [
        [
         {
          "params": [
           "bundle-transmitted-messages__ack"
          ],
          "type": "field"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "Bundle TX HELLO, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
       "query": "SELECT \"bundle-received-messages__hello\" FROM \"Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message\" WHERE \"Producer\" =~ /^$Node$/ AND \"interface-name\" =~ /Bundle.*/ AND $timeFilter GROUP BY \"interface-name\"",
       "select": [
        [
         {
          "params": [
           "bundle-transmitted-messages__hello"
          ],
          "type": "field"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "Bundle TX PATH, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
       "query": "SELECT \"bundle-received-messages__hello\" FROM \"Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message\" WHERE \"Producer\" =~ /^$Node$/ AND \"interface-name\" =~ /Bundle.*/ AND $timeFilter GROUP BY \"interface-name\"",
       "select": [
        [
         {
          "params": [
           "bundle-transmitted-messages__path"
          ],
          "type": "field"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "Bundle TX PATH ERROR, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
       "query": "SELECT \"bundle-received-messages__hello\" FROM \"Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message\" WHERE \"Producer\" =~ /^$Node$/ AND \"interface-name\" =~ /Bundle.*/ AND $timeFilter GROUP BY \"interface-name\"",
       "select": [
        [
         {
          "params": [
           "bundle-transmitted-messages__path-error"
          ],
          "type": "field"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "Bundle TX PATH TEAR, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
       "query": "SELECT \"bundle-received-messages__hello\" FROM \"Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message\" WHERE \"Producer\" =~ /^$Node$/ AND \"interface-name\" =~ /Bundle.*/ AND $timeFilter GROUP BY \"interface-name\"",
       "select": [
        [
         {
          "params": [
           "bundle-transmitted-messages__path-tear"
          ],
          "type": "field"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "Bundle TX RESV, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
       "query": "SELECT \"bundle-received-messages__hello\" FROM \"Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message\" WHERE \"Producer\" =~ /^$Node$/ AND \"interface-name\" =~ /Bundle.*/ AND $timeFilter GROUP BY \"interface-name\"",
       "select": [
        [
         {
          "params": [
           "bundle-transmitted-messages__reservation"
          ],
          "type": "field"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "Bundle TX RESV CONFIRM, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
       "query": "SELECT \"bundle-received-messages__hello\" FROM \"Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message\" WHERE \"Producer\" =~ /^$Node$/ AND \"interface-name\" =~ /Bundle.*/ AND $timeFilter GROUP BY \"interface-name\"",
       "select": [
        [
         {
          "params": [
           "bundle-transmitted-messages__reservation-confirm"
          ],
          "type": "field"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "Bundle TX RESV ERROR, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
       "query": "SELECT \"bundle-received-messages__hello\" FROM \"Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message\" WHERE \"Producer\" =~ /^$Node$/ AND \"interface-name\" =~ /Bundle.*/ AND $timeFilter GROUP BY \"interface-name\"",
       "select": [
        [
         {
          "params": [
           "bundle-transmitted-messages__reservation-error"
          ],
          "type": "field"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "Bundle TX RESV TEAR, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
       "query": "SELECT \"bundle-received-messages__hello\" FROM \"Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message\" WHERE \"Producer\" =~ /^$Node$/ AND \"interface-name\" =~ /Bundle.*/ AND $timeFilter GROUP BY \"interface-name\"",
       "select": [
        [
         {
          "params": [
           "bundle-transmitted-messages__reservation-tear"
          ],
          "type": "field"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "RX ACK, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
       "select": [
        [
         { "params": [ "received-messages__ack" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "RX HELLO, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
       "query": "SELECT \"bundle-received-messages__hello\" FROM \"Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message\" WHERE \"Producer\" =~ /^$Node$/ AND \"interface-name\" =~ /Bundle.*/ AND $timeFilter GROUP BY \"interface-name\"",
       "select": [
        [
         { "params": [ "received-messages__hello" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "RX PATH, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
       "query": "SELECT \"bundle-received-messages__hello\" FROM \"Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message\" WHERE \"Producer\" =~ /^$Node$/ AND \"interface-name\" =~ /Bundle.*/ AND $timeFilter GROUP BY \"interface-name\"",
       "select": [
        [
         { "params": [ "received-messages__path" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "RX PATH ERROR, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
       "query": "SELECT \"bundle-received-messages__hello\" FROM \"Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message\" WHERE \"Producer\" =~ /^$Node$/ AND \"interface-name\" =~ /Bundle.*/ AND $timeFilter GROUP BY \"interface-name\"",
       "select": [
        [
         { "params": [ "received-messages__path-error" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "RX PATH TEAR, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
       "query": "SELECT \"bundle-received-messages__hello\" FROM \"Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message\" WHERE \"Producer\" =~ /^$Node$/ AND \"interface-name\" =~ /Bundle.*/ AND $timeFilter GROUP BY \"interface-name\"",
       "select": [
        [
         { "params": [ "received-messages__path-tear" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "RX RESV, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
       "query": "SELECT \"bundle-received-messages__hello\" FROM \"Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message\" WHERE \"Producer\" =~ /^$Node$/ AND \"interface-name\" =~ /Bundle.*/ AND $timeFilter GROUP BY \"interface-name\"",
       "select": [
        [
         { "params": [ "received-messages__reservation" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "RX RESV CONFIRM, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
       "query": "SELECT \"bundle-received-messages__hello\" FROM \"Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message\" WHERE \"Producer\" =~ /^$Node$/ AND \"interface-name\" =~ /Bundle.*/ AND $timeFilter GROUP BY \"interface-name\"",
       "select": [
        [
         {
          "params": [
           "received-messages__reservation-confirm"
          ],
          "type": "field"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "RX RESV ERROR, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
       "query": "SELECT \"bundle-received-messages__hello\" FROM \"Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message\" WHERE \"Producer\" =~ /^$Node$/ AND \"interface-name\" =~ /Bundle.*/ AND $timeFilter GROUP BY \"interface-name\"",
       "select": [
        [
         {
          "params": [
           "received-messages__reservation-error"
          ],
          "type": "field"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "RX RESV TEAR, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
       "query": "SELECT \"bundle-received-messages__hello\" FROM \"Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message\" WHERE \"Producer\" =~ /^$Node$/ AND \"interface-name\" =~ /Bundle.*/ AND $timeFilter GROUP BY \"interface-name\"",
       "select": [
        [
         {
          "params": [
           "received-messages__reservation-tear"
          ],
          "type": "field"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "TX ACK, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
       "select": [
        [
         { "params": [ "transmitted-messages__ack" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "TX HELLO, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
       "query": "SELECT \"bundle-received-messages__hello\" FROM \"Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message\" WHERE \"Producer\" =~ /^$Node$/ AND \"interface-name\" =~ /Bundle.*/ AND $timeFilter GROUP BY \"interface-name\"",
       "select": [
        [
         { "params": [ "transmitted-messages__hello" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "TX PATH, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
       "query": "SELECT \"bundle-received-messages__hello\" FROM \"Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message\" WHERE \"Producer\" =~ /^$Node$/ AND \"interface-name\" =~ /Bundle.*/ AND $timeFilter GROUP BY \"interface-name\"",
       "select": [
        [
         { "params": [ "transmitted-messages__path" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "TX PATH ERROR, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
       "query": "SELECT \"bundle-received-messages__hello\" FROM \"Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message\" WHERE \"Producer\" =~ /^$Node$/ AND \"interface-name\" =~ /Bundle.*/ AND $timeFilter GROUP BY \"interface-name\"",
       "select": [
        [
         {
          "params": [
           "transmitted-messages__path-error"
          ],
          "type": "field"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" },
        { "condition": "AND", "key": "interface-name", "operator": "=~", "value": "/Bundle.*/" }
       ]
      },
      {
       "alias": "TX PATH TEAR, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
       "query": "SELECT \"bundle-received-messages__hello\" FROM \"Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message\" WHERE \"Producer\" =~ /^$Node$/ AND \"interface-name\" =~ /Bundle.*/ AND $timeFilter GROUP BY \"interface-name\"",
       "select": [
        [
         {
          "params": [
           "transmitted-messages__path-tear"
          ],
          "type": "field"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "TX RESV, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
       "query": "SELECT \"bundle-received-messages__hello\" FROM \"Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message\" WHERE \"Producer\" =~ /^$Node$/ AND \"interface-name\" =~ /Bundle.*/ AND $timeFilter GROUP BY \"interface-name\"",
       "select": [
        [
         {
          "params": [
           "transmitted-messages__reservation"
          ],
          "type": "field"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "TX RESV CONFIRM, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
       "query": "SELECT \"bundle-received-messages__hello\" FROM \"Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message\" WHERE \"Producer\" =~ /^$Node$/ AND \"interface-name\" =~ /Bundle.*/ AND $timeFilter GROUP BY \"interface-name\"",
       "select": [
        [
         {
          "params": [
           "transmitted-messages__reservation-confirm"
          ],
          "type": "field"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "TX RESV ERROR, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
       "query": "SELECT \"bundle-received-messages__hello\" FROM \"Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message\" WHERE \"Producer\" =~ /^$Node$/ AND \"interface-name\" =~ /Bundle.*/ AND $timeFilter GROUP BY \"interface-name\"",
       "select": [
        [
         {
          "params": [
           "transmitted-messages__reservation-error"
          ],
          "type": "field"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "TX RESV TEAR, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
       "query": "SELECT \"transmitted-messages__reservation-tear\" FROM \"Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message\" WHERE (\"Producer\" =~ /^$Node$/) AND $timeFilter GROUP BY \"interface-name\"",
       "select": [
        [
         {
          "params": [
           "transmitted-messages__reservation-tear"
          ],
          "type": "field"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      }
     ]
    },
    {
     "title": "RSVP MAX per interface",
     "type": "table-old",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 77 },
     "targets": [
      {
       "alias": "MAX RSVP BW, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/interface-briefs/interface-brief",
       "select": [
        [
         {
          "params": [
           "bandwidth-information__pre-standard-dste-interface__max-flow-bandwidth"
          ],
          "type": "field"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      }
     ]
    },
    {
     "title": "RSVP allocation per interface",
     "type": "table-old",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 77 },
     "targets": [
      {
       "alias": "Allocated RSVP BW, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/interface-briefs/interface-brief",
       "query": "SELECT \"bandwidth-information__pre-standard-dste-interface__allocated-bit-rate\" FROM \"Cisco-IOS-XR-ip-rsvp-oper:rsvp/interface-briefs/interface-brief\" WHERE \"Producer\" =~ /^$Node$/ AND \"interface-name\" =~ /Bundle.*/ AND $timeFilter GROUP BY \"interface-name\"",
       "select": [
        [
         {
          "params": [
           "bandwidth-information__pre-standard-dste-interface__allocated-bit-rate"
          ],
          "type": "field"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      }
     ]
    },
    {
     "title": "RSVP FREE Bandwidth per interface",
     "type": "table-old",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 77 },
     "targets": [
      {
       "alias": "Free RSVP BW, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/interface-briefs/interface-brief",
       "query": "SELECT (\"bandwidth-information__pre-standard-dste-interface__max-flow-bandwidth\" - \"bandwidth-information__pre-standard-dste-interface__allocated-bit-rate\" ) FROM \"Cisco-IOS-XR-ip-rsvp-oper:rsvp/interface-briefs/interface-brief\" WHERE \"Producer\" =~ /^$Node$/ AND \"interface-name\" =~ /Bundle.*/ AND $timeFilter GROUP BY \"interface-name\"",
       "select": [
        [
         {
          "params": [
           "bandwidth-information__pre-standard-dste-interface__max-flow-bandwidth"
          ],
          "type": "field"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      }
     ]
    },
    {
     "title": "RSVP messages stats",
     "type": "table-old",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 77 },
     "targets": [
      {
       "alias": "Bundle RX ACK, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
       "select": [
        [
         { "params": [ "bundle-received-messages__ack" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "Bundle RX HELLO, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
       "select": [
        [
         {
          "params": [
           "bundle-received-messages__hello"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "Bundle RX PATH, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
       "select": [
        [
         { "params": [ "bundle-received-messages__path" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "Bundle RX PATH-ERROR, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
       "select": [
        [
         {
          "params": [
           "bundle-received-messages__path-error"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "Bundle RX PATH-TEAR, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
       "select": [
        [
         {
          "params": [
           "bundle-received-messages__path-tear"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "Bundle RX RESV, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
       "select": [
        [
         {
          "params": [
           "bundle-received-messages__reservation"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "Bundle RX RESV CONFIRM, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
       "select": [
        [
         {
          "params": [
           "bundle-received-messages__reservation-confirm"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "Bundle RX RESV ERROR, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
       "select": [
        [
         {
          "params": [
           "bundle-received-messages__reservation-error"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "Bundle RX RESV TEAR, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
       "select": [
        [
         {
          "params": [
           "bundle-received-messages__reservation-tear"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "Bundle TX ACK, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
       "select": [
        [
         {
          "params": [
           "bundle-transmitted-messages__ack"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "Bundle TX HELLO, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
       "select": [
        [
         {
          "params": [
           "bundle-transmitted-messages__hello"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "Bundle TX PATH, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
       "select": [
        [
         {
          "params": [
           "bundle-transmitted-messages__path"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "Bundle TX PATH-ERROR, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
       "select": [
        [
         {
          "params": [
           "bundle-transmitted-messages__path-error"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "Bundle TX PATH-TEAR, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
       "select": [
        [
         {
          "params": [
           "bundle-transmitted-messages__path-tear"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "Bundle TX RESV, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
       "select": [
        [
         {
          "params": [
           "bundle-transmitted-messages__reservation"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "Bundle TX RESV CONFIRM, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
       "select": [
        [
         {
          "params": [
           "bundle-transmitted-messages__reservation-confirm"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "Bundle TX RESV ERROR, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
       "select": [
        [
         {
          "params": [
           "bundle-transmitted-messages__reservation-error"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "Bundle TX RESV TEAR, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
       "select": [
        [
         {
          "params": [
           "bundle-transmitted-messages__reservation-tear"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "RX ACK, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
       "select": [
        [
         { "params": [ "received-messages__ack" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "RX HELLO, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
       "select": [
        [
         { "params": [ "received-messages__hello" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "RX PATH, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
       "select": [
        [
         { "params": [ "received-messages__path" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "RX PATH-ERROR, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
       "select": [
        [
         { "params": [ "received-messages__path-error" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "RX PATH-TEAR, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
       "select": [
        [
         { "params": [ "received-messages__path-tear" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "RX RESV, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
       "select": [
        [
         { "params": [ "received-messages__reservation" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "RX RESV CONFIRM, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
       "select": [
        [
         {
          "params": [
           "received-messages__reservation-confirm"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "Bundle RX RESV ERROR, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
       "select": [
        [
         {
          "params": [
           "bundle-received-messages__reservation-error"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "RX RESV TEAR, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
       "select": [
        [
         {
          "params": [
           "received-messages__reservation-tear"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "TX ACK, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
       "select": [
        [
         { "params": [ "transmitted-messages__ack" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "TX HELLO, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
       "select": [
        [
         { "params": [ "transmitted-messages__hello" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "TX PATH, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
       "select": [
        [
         { "params": [ "transmitted-messages__path" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "TX PATH-ERROR, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
       "select": [
        [
         {
          "params": [
           "transmitted-messages__path-error"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "TX PATH-TEAR, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
       "select": [
        [
         {
          "params": [
           "transmitted-messages__path-tear"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "TX RESV, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
       "select": [
        [
         {
          "params": [
           "transmitted-messages__reservation"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "TX RESV CONFIRM, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
       "select": [
        [
         {
          "params": [
           "transmitted-messages__reservation-confirm"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "TX RESV ERROR, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
       "select": [
        [
         {
          "params": [
           "transmitted-messages__reservation-error"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      },
      {
       "alias": "TX RESV TEAR, [[tag_interface-name]]",
       "groupBy": [
        { "params": [ "interface-name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
       "select": [
        [
         {
          "params": [
           "transmitted-messages__reservation-tear"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "Producer", "operator": "=~", "value": "/^$Node$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}