cmts:
  community_string: read
  port: 161
  oids:
  - mib: SNMPv2-MIB
    oid: sysDescr
    endpoint: 0
#  - mib: SNMPv2-MIB
#    oid: sysDescr
#    endpoint: 0
#  - mib: SNMPv2-MIB
#    oid: sysDescr
#    endpoint: 0
#  - mib: SNMPv2-MIB
#    oid: sysDescr
#    endpoint: 0
cm:
  community_string: public
  port: 161
  oids:
  - mib: SNMPv2-MIB
    oid: sysDescr
    endpoint: 0
#  - mib: SNMPv2-MIB
#    oid: sysDescr
#    endpoint: 0
#  - mib: SNMPv2-MIB
#    oid: sysDescr
#    endpoint: 0
#  - mib: SNMPv2-MIB
#    oid: sysDescr
#    endpoint: 0