---

# InfluxDB configuration
influxdb:
  host: 172.28.128.10
  port: 8086
  snmp_db: snmp
  create_db: True

# CMTS configuration
cmts:
  community_string: read
  port: 161
  oids:
  - mib: SNMPv2-MIB
    oid: sysDescr
    endpoint: 0
  - mib: DOCS-RPHY-MIB
    oid: docsRphyRpdIfEnetPhysAddress
    endpoint: 0

# Cable Modem Configuration
cm:
  community_string: public
  port: 161
  oids:
  - mib: SNMPv2-MIB
    oid: sysDescr
    endpoint: 0
#  - mib: SNMPv2-MIB
#    oid: sysDescr
#    endpoint: 0
