---

# InfluxDB configuration
influxdb:
  host: 10.89.188.28
  port: 8086
  snmp_db: snmp
  create_db: True

# CMTS configuration
cmts:
  community_string: read
  port: 161
  oids:
  - mib: SNMPv2-MIB
    oid: sysDescr
    endpoint: 0
#  - mib: SNMPv2-MIB
#    oid: sysDescr
#    endpoint: 0

# Cable Modem Configuration
cm:
  community_string: public
  port: 161
  oids:
  - mib: SNMPv2-MIB
    oid: sysDescr
    endpoint: 0
#  - mib: SNMPv2-MIB
#    oid: sysDescr
#    endpoint: 0
