---
- hosts: 127.0.0.1
  port: 2222
  vars:
    - docker_users:
      - "{{ ansible_env.USER }}"
  vars_files:
      - vars.yml

  tasks:

    - name: Render IOSXE Config
      template:
          src: ../files/config snippets/iosxe-config.j2
          dest: ../xe-config.txt

    - name: Render IOSXR Config
      template:
          src: ../files/config snippets/iosxr-config.j2
          dest: ../xr-config.txt