---
- hosts: docker0
  vars:
    - docker_users:
      - "{{ ansible_env.USER }}"
  vars_files:
    - vars.yml


  pre_tasks:
    - name: Set permenant environment variables
      become: true
      lineinfile:
        dest: /etc/environment
        regexp: "{{item.regexp}}"
        line: "{{item.line}}"
      with_items:
        - { regexp: '^PUID=', line: 'PUID={{ ansible_env.USER }}' }
        - { regexp: '^PGID=', line: 'PGID=998' }
        - { regexp: '^DOCKERDIR=', line: 'DOCKERDIR="{{ ansible_env.HOME }}/docker"' }
        - { regexp: '^TZ=', line: 'TZ="America/New York"' }

    - name: Update package cache and install APT packages
      become: true
      package:
        name: [ python3-pip ]
        state: present
        update_cache: true
        cache_valid_time: 3600

    - name: Install pip packages
      pip:
        name: [ docker-compose, docker ]
        executable: pip3
        state: present

  tasks:
    - block:
      - name: Bring up docker
        include_role:
          name: geerlingguy.docker
      become: true
    
    - name: Copy docker directory to remote server
      copy:
        src: ../files/docker
        dest: "{{ ansible_env.HOME }}"

    - name: Render IOSXE Config
      template:
          src: ../files/config snippets/iosxe-config.j2
          dest: ~/xe-config.txt
      tags:
        - render

    - name: Render IOSXR Config
      template:
          src: ../files/config snippets/iosxr-config.j2
          dest: ~/xr-config.txt
      tags:
        - render

    - name: Render cBR8 Dashboards
      template:
          src: '{{ item.src }}'
          dest: '{{ item.dest }}'
      with_items:
          - { src: '../files/templates/grafana/dashboards/cbr8/cbr8_overview.j2', dest: '~/docker/grafana/provisioning/dashboards/cbr8/cbr8_overview.json' }
          - { src: '../files/templates/grafana/dashboards/cbr8/cbr8_detail.j2', dest: '~/docker/grafana/provisioning/dashboards/cbr8/cbr8_detail.json' }
          - { src: '../files/templates/grafana/dashboards/cbr8/service_group.j2', dest: '~/docker/grafana/provisioning/dashboards/cbr8/service_group.json' }
          - { src: '../files/templates/grafana/dashboards/cbr8/cable_modem_detail.j2', dest: '~/docker/grafana/provisioning/dashboards/cbr8/cable_modem_detail.json' }
          - { src: '../files/templates/grafana/dashboards/cbr8/partial_mode_detail.j2', dest: '~/docker/grafana/provisioning/dashboards/cbr8/partial_mode_detail.json' }
      tags:
        - render
    # - debug:
        # msg: Log out of server and back in again then run 'docker-compose -f {{ ansible_env.HOME/docker/docker-compose.yml }} up -d'
